version: '3.1'

services:
    postgres:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_USER: Admin
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: Car
        ports:
           - 5432:5432
           